### ISSUE TITLE
How to train and run this on LSR2 dataset?

### ISSUE THREAD

**Issue by jainnimish** [theSoenke/lipreading#2]
Hello, 
Can you please provide step by step instructions on how to train and run this repo on LSR2 dataset? I want to then run the trained model to predict what a user is saying in a video. 

Regards.

**Comment by theSoenke** [comment]
Hi, do the steps from the readme work for you? https://github.com/theSoenke/lipreading#lrs2

**Comment by jainnimish** [comment]
The training part works for me but I don't know how to test the model on an actual video. That's what I need help with.

**Comment by theSoenke** [comment]
I've not worked with this code in a while but basically you'll have have to instantiate a model:
```
model = LRS2ResnetAttn(
  hparams=args,
  in_channels=1,
)
```

Then load a checkpoint
```
checkpoint = torch.load(checkpoint)
model.load_state_dict(checkpoint['state_dict'])
```

Finally pass in some data. You could use the training step as a inspiration on how to pass in data: https://github.com/theSoenke/lipreading/blob/master/src/models/lrs2_resnet_attn.py#L212 This will also require a bit of preprocessing to crop the head from a video for which I recommend to look a the preprocessing code and data loader.

**Comment by jainnimish** [comment]
Thank you very much! Just one more question: How can you generate a weights file (.h5) for the trained model? I'm new to machine learning and have just started a couple weeks back. Cheers!

**Comment by theSoenke** [comment]
No problem! The code in its current state has not really been developed to be easily usable with new data.  The `.h5` file is only used for the LRW model as the output of the preprocessing. 

For LRS2 I would suggest to look into the facial landmark extraction here: https://github.com/theSoenke/lipreading/blob/master/src/preprocess/lrs2.py#L237

The generated bounding box can then be used to crop the video and prepare a tensor for the model: https://github.com/theSoenke/lipreading/blob/master/src/data/lrs2.py#L94

**Comment by jainnimish** [comment]
Thank you very much! Really appreciate you for all the help.
